# Generated by Django 4.2.2 on 2023-08-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subTitle',
        ),
    ]
