# Generated by Django 4.2.2 on 2023-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('name', models.CharField(max_length=116)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
